### ISSUE TITLE
`liquid` is a potential user

### ISSUE THREAD

**Issue by Jake-Shadle** [MiSawa/time-fmt#1]
This crate popped up after I had already started working on it, but

- https://github.com/cobalt-org/liquid-rust/pull/460

is a PR that `strftime` on top of `time` specifically for the `liquid` use case of formatting date times with user provided format strings that might be interesting for this crate to be used for instead. As noted in the PR I've already spent more time than I would like doing that PR, so I don't have the energy/time to do this myself, but thought I would open this issue here in the hopes the maintainers of this crate and the liquid repo can collaborate together.

**Comment by MiSawa** [comment]
Ah hmm, same situation here. I have a [Rust clone of jq](https://github.com/MiSawa/xq) which runs `strftime`/`strptime` with user provided format strings.
It'd take some time if you'd want me to make this match the Ruby spec, though contributions are always welcomed!
