### ISSUE TITLE
Vec<FormatItem> produce seems to not work properly with time-rs

### ISSUE THREAD

**Issue by evanxg852000** [MiSawa/time-fmt#11]
It looks like format spec `Vec<FormatItem>` produced by `ToFormatItemCollector` does not work properly when passed to time-rs `PrimitiveDateTime::parse` or `OffsetDateTime::parse`.
I tried parsing this ` 2012-05-21 12:09:14` with a `Vec<FormatItem>` produced from `Y-%m-%d %H:%M:%S` and this was the error:
```
Err("the Parsed struct did not include enough information to construct the type")
```

**Comment by MiSawa** [comment]
@evanxg852000 I've added a couple of tests in [5abd6ed](https://github.com/MiSawa/time-fmt/commit/5abd6ed8269e0dfbcb6eb4fcd5b7aa640ea1e971), and it seemingly working. Could you please provide a concrete `#[test]` that fails?

**Comment by evanxg852000** [comment]
@MiSawa  Thanks for the follow up.
I updated the `time-rs` version I am depending on and the format work. 
I still have issue as it seems right now there is no support to build a  `Vec<FormatItem>` that can parse `2012/05/21 12:09:14 +02:00`  (time offset like `+02:00` ).

It would be nice to have:  `%:z` - hour and minute offset from UTC with a colon (e.g. +09:00) that generates
`[offset_hour sign:mandatory]:[offset_minute]`

Here is a test for what I am talking about
```rust
    #[test]
    fn parse_offset_datetime_error() -> Result<(), Box<dyn std::error::Error>> {
        // Colon is accepted here `-03:00`
        let (_, time_zone_opt) = parse_strict_date_time_maybe_with_zone("%Y-%m-%d %H:%M:%S %z", "2012-05-21 12:09:14 -03:00")?;
        assert_eq!(
            time_zone_opt,
            Some(TimeZoneSpecifier::Offset(offset!(-3)))
        );
        
        let format_items = parse_to_format_item("%Y-%m-%d %H:%M:%S %z")?;
        // Fails to parse: `Error: ParseFromDescription(InvalidComponent("offset minute"))`
        // I would expect this offset `-03:00` to be accepted as well or both get reject since the `:` is not conform to %z
        assert_eq!(
            OffsetDateTime::parse("2012-05-21 12:09:14 -03:00", &format_items)?,
            datetime!(2012-05-21 12:09:14 -03:00)
        );
        Ok(())
    }
```

**Comment by evanxg852000** [comment]
As an amendment, the `%z` specifier is  "An RFC-822/ISO 8601 standard timezone specification."
According to https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators, it accepts  colon `+01:00`

**Comment by MiSawa** [comment]
Actually I was wrong. Although the example in my previous comment "works", it shouldn't have been used in that way. As the module name suggests, the return value of `format::parse_to_format_items` should be used to *format* a time to string, not to *parse* a string to time.
I guess what you'd want implemented is the `parse::` version of the function that would emit more complicated `FormatItem`s for case insensitivity, colon and such ambiguities.

**Comment by evanxg852000** [comment]
Right now the changes I just need is to modify `ToFormatItemCollector::timezone`
```rust
self.items.push(FormatItem::Optional(&FormatItem::Literal(b":")));
```
I just want to support parsing `+00:00` and `+0000` for now. If that's OK, I can open a PR with a parse version that does this. 
My only concern is: it might be almost a carbon copy of what's in `ToFormatItemCollector` or maybe we can introduce an intermediate trait in order to reuse.

**Comment by MiSawa** [comment]
@evanxg852000 Oops sorry, I was already started implementing it. And... you can now use `parse::parse_to_format_items` from v0.3.8!

**Comment by evanxg852000** [comment]
No need to be sorry, Thanks a lot, I am grateful.
